on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: Build and Push Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repository: [
          "map-even-odd", "map-flatmap", "map-forward-message", "map-retry", "map-tickgen",
          "map-flatmap-stream", "reduce-counter", "reduce-sum", "reduce-stream-counter",
          "reduce-stream-sum", "session-counter", "sideinput-example", "udf-sideinput-example",
          "sink-log", "source-simple-source", "mapt-assign-event-time", "mapt-event-time-filter"
        ]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Quay.io registry
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ env.QUAY_USERNAME }}
          password: ${{ env.QUAY_PASSWORD }}
      - name: Build and tag images
        run: ./update_examples --build
      - name: Push images
        env:
          IMAGE_PREFIX: "quay.io/numaio/numaflow-go"
          TAG: "stable"
        run: |
          docker push ${{ env.IMAGE_PREFIX }}/${{ matrix.repository }}:${{ env.TAG }}
