name: Docker Publish

on:
  push:
    branches: [ test-ci ]
    tags:
      - '*'

jobs:
  build_push_examples:
    name: Build and Push Images
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 6
      matrix:
        repository: [
          "sideinput-example", "udf-sideinput-example"
#          "map-even-odd",
#          "map-flatmap", "map-forward-message", "map-retry", "map-tickgen",
#          "map-flatmap-stream", "reduce-counter", "reduce-sum", "reduce-stream-counter",
#          "reduce-stream-sum", "session-counter", "sideinput-example", "udf-sideinput-example",
#          "sink-log", "source-simple-source", "mapt-assign-event-time", "mapt-event-time-filter"
        ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Quay.io registry
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.NUMAIO_USERNAME }}
          password: ${{ secrets.NUMAIO_PASSWORD }}
      - name: Build, tag, and push images
        run: ./update_examples.sh --build-push
